# title of website
title: Example site

# description of website
description: Site description

# favicon of website
favicon: https://when.run/avator.jpeg

# your website url
url: https://example.com

# github profile url
github: https://github.com/ggbond-cc

# footer message
footer: © 2017-2020 WebStack design by Viggo

# template(theme) of your site, available:
# 1. webstack (http://webstack.cc)
template: webstack

google_analytics: "G-EXE1PJ8CR2"


webstack:
  search:
    enabled: true
    default: google
    # 可选的搜索引擎
    engines:
      - google
      - github
      - baidu
      - zhihu
      - weibo
      - bilibili
      - douban
      - sougou
      - bing


content:
  categories:
    - name: 常用推荐
      sites:
        - name: blog
          description: ggbond's blog
          url: https://blog.ggbond.cc
          logo: https://www.baidu.com